### PR TITLE
Clauses support - fixes #17

### LINKED ISSUE #17: Support: WHERE/HAVING/GROUP BY/UNION clauses
https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-us/abencds_select_clauses.htm

### PR DESCRIPTION
**Pull request by esjewett**

### CODE REVIEW

**Comment by larshp** [comment]
the pull requests seem very large, I guess the auto generated code is also in git? You can consider not putting the auto generated stuff in git

**Comment by esjewett** [comment]
@larshp Good point - just excluded those on the master branch. They shouldn't show up in the future.

**Comment by larshp** [comment]
also see https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches, github can automatically delete the feature branches after merge if you like

**Comment by esjewett** [comment]
@larshp Done :)

**Pull request merged**
